### ISSUE TITLE
курсор кликает не там в SU22

### ISSUE THREAD

**Issue by bobecka** [neproger/cutting_helper#1]
https://github.com/neproger/cutting_helper/blob/87e7f9475ec064f518a31f70a7c227e71636a4e8/cutting_tool.rb#L14

в SU22, курсор так и остается огромного размера, как png и клацает не туда. Для исправления нужно png уменьшить до 32х32 и поставить в этой строчке 16 вместо 42. тогда будет полная совместимость

**Comment by neproger** [comment]
сделал как вы сказали. но вместо png переделал в svg. оказывается так можно было)
