### ISSUE TITLE
В настройках ошибка

### ISSUE THREAD

**Issue by bobecka** [neproger/cutting_helper#2]
При нажатии на вычитать кромки, меняется чекбокс у темы на светлую\темную. Ну и самому нельзя менять тему.

**Comment by bobecka** [comment]
и в крое не вычитается кромка

**Comment by neproger** [comment]
> При нажатии на вычитать кромки, меняется чекбокс у темы на светлую\темную. Ну и самому нельзя менять тему.

начал делать светлую тему, но пока руки не доходят доделать.

**Comment by neproger** [comment]
> и в крое не вычитается кромка

поправил, вроде теперь все хоршо. но надо тестить)

**Comment by neproger** [comment]
> При нажатии на вычитать кромки, меняется чекбокс у темы на светлую\темную. Ну и самому нельзя менять тему.

чекбокс убрал потому что логики смены темы пока нет, и времени нет этим заниматься)
